config:

  # Just some info stuff; not used by the patching scripts
<<<<<<< HEAD:patch/kernel/archive/rockchip-6.10/0000.patching_config.yaml
<<<<<<<< HEAD:patch/kernel/rk35xx-nanopi-6.1.y/0000.patching_config.yaml
  name: rk35xx-nanopi-6.1.y
  kind: kernel
  type: nanopi
  branch: nanopi6-v6.1.y
  last-known-good-tag: v6.1.y
========
  name: rockchip-6.10
=======
  name: rockchip-6.12
>>>>>>> 91978d7e6a913507d6ce36bc324eb698b42d20c1:patch/kernel/archive/rockchip-6.12/0000.patching_config.yaml
  kind: kernel
  type: mainline # or: vendor
  branch: linux-6.12.y
  last-known-good-tag: v6.12
  maintainers:
    - { github: paolo.sabatino, name: Paolo Sabatino, email: paolo.sabatino@gmail.com, armbian-forum: jock }
>>>>>>>> 468342d3f75f6696f99d388b5b76f1b35c5e44d3:patch/kernel/archive/rockchip-6.10/0000.patching_config.yaml

  # .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
  # This is meant to provide a way to "add a board DTS" without having to null-patch them in.
  dts-directories:
    - { source: "dt", target: "arch/arm64/boot/dts/rockchip" }

  # the Makefile in each of these directories will be magically patched to include the dts files copied
  #  or patched-in; overlay subdir will be included "-y" if it exists.
  # No more Makefile patching needed, yay!
  # "incremental: true" changes the logic of the Makefile re-writing to only add the
  #                     dts-directories's *.dts files to existing Makefile instead of
  #                     full rewrite from *.dts in the dt dir at the end of patching.
  auto-patch-dt-makefile:
    - { incremental: true, directory: "arch/arm64/boot/dts/rockchip", config-var: "CONFIG_ARCH_ROCKCHIP" }

  # configuration for when applying patches to git / auto-rewriting patches (development cycle helpers)
  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS" # constant churn, drop them. sorry.
      - "Documentation/devicetree/bindings/arm/rockchip.yaml" # constant churn, conflicts on every bump, drop it. sorry.
    do-not-commit-regexes: # Python-style regexes
      - "^arch/([a-zA-Z0-9]+)/boot/dts/([a-zA-Z0-9]+)/Makefile$" # ignore DT Makefile patches, we've an auto-patcher now

